// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: websocket/v1/message.proto

package websocketv1

import (
	v1 "github.com/trysourcetool/sourcetool-go/internal/pb/exception/v1"
	v11 "github.com/trysourcetool/sourcetool-go/internal/pb/page/v1"
	v12 "github.com/trysourcetool/sourcetool-go/internal/pb/widget/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptFinished_Status int32

const (
	ScriptFinished_STATUS_UNSPECIFIED ScriptFinished_Status = 0
	ScriptFinished_STATUS_SUCCESS     ScriptFinished_Status = 1
	ScriptFinished_STATUS_FAILURE     ScriptFinished_Status = 2
)

// Enum value maps for ScriptFinished_Status.
var (
	ScriptFinished_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_FAILURE",
	}
	ScriptFinished_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_FAILURE":     2,
	}
)

func (x ScriptFinished_Status) Enum() *ScriptFinished_Status {
	p := new(ScriptFinished_Status)
	*p = x
	return p
}

func (x ScriptFinished_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScriptFinished_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_websocket_v1_message_proto_enumTypes[0].Descriptor()
}

func (ScriptFinished_Status) Type() protoreflect.EnumType {
	return &file_websocket_v1_message_proto_enumTypes[0]
}

func (x ScriptFinished_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScriptFinished_Status.Descriptor instead.
func (ScriptFinished_Status) EnumDescriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{8, 0}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Message_Exception
	//	*Message_InitializeHost
	//	*Message_InitializeHostCompleted
	//	*Message_InitializeClient
	//	*Message_InitializeClientCompleted
	//	*Message_RenderWidget
	//	*Message_RerunPage
	//	*Message_CloseSession
	//	*Message_ScriptFinished
	Type          isMessage_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_websocket_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetType() isMessage_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Message) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Type.(*Message_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

func (x *Message) GetInitializeHost() *InitializeHost {
	if x != nil {
		if x, ok := x.Type.(*Message_InitializeHost); ok {
			return x.InitializeHost
		}
	}
	return nil
}

func (x *Message) GetInitializeHostCompleted() *InitializeHostCompleted {
	if x != nil {
		if x, ok := x.Type.(*Message_InitializeHostCompleted); ok {
			return x.InitializeHostCompleted
		}
	}
	return nil
}

func (x *Message) GetInitializeClient() *InitializeClient {
	if x != nil {
		if x, ok := x.Type.(*Message_InitializeClient); ok {
			return x.InitializeClient
		}
	}
	return nil
}

func (x *Message) GetInitializeClientCompleted() *InitializeClientCompleted {
	if x != nil {
		if x, ok := x.Type.(*Message_InitializeClientCompleted); ok {
			return x.InitializeClientCompleted
		}
	}
	return nil
}

func (x *Message) GetRenderWidget() *RenderWidget {
	if x != nil {
		if x, ok := x.Type.(*Message_RenderWidget); ok {
			return x.RenderWidget
		}
	}
	return nil
}

func (x *Message) GetRerunPage() *RerunPage {
	if x != nil {
		if x, ok := x.Type.(*Message_RerunPage); ok {
			return x.RerunPage
		}
	}
	return nil
}

func (x *Message) GetCloseSession() *CloseSession {
	if x != nil {
		if x, ok := x.Type.(*Message_CloseSession); ok {
			return x.CloseSession
		}
	}
	return nil
}

func (x *Message) GetScriptFinished() *ScriptFinished {
	if x != nil {
		if x, ok := x.Type.(*Message_ScriptFinished); ok {
			return x.ScriptFinished
		}
	}
	return nil
}

type isMessage_Type interface {
	isMessage_Type()
}

type Message_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,2,opt,name=exception,proto3,oneof"`
}

type Message_InitializeHost struct {
	InitializeHost *InitializeHost `protobuf:"bytes,3,opt,name=initialize_host,json=initializeHost,proto3,oneof"`
}

type Message_InitializeHostCompleted struct {
	InitializeHostCompleted *InitializeHostCompleted `protobuf:"bytes,4,opt,name=initialize_host_completed,json=initializeHostCompleted,proto3,oneof"`
}

type Message_InitializeClient struct {
	InitializeClient *InitializeClient `protobuf:"bytes,5,opt,name=initialize_client,json=initializeClient,proto3,oneof"`
}

type Message_InitializeClientCompleted struct {
	InitializeClientCompleted *InitializeClientCompleted `protobuf:"bytes,6,opt,name=initialize_client_completed,json=initializeClientCompleted,proto3,oneof"`
}

type Message_RenderWidget struct {
	RenderWidget *RenderWidget `protobuf:"bytes,7,opt,name=render_widget,json=renderWidget,proto3,oneof"`
}

type Message_RerunPage struct {
	RerunPage *RerunPage `protobuf:"bytes,8,opt,name=rerun_page,json=rerunPage,proto3,oneof"`
}

type Message_CloseSession struct {
	CloseSession *CloseSession `protobuf:"bytes,9,opt,name=close_session,json=closeSession,proto3,oneof"`
}

type Message_ScriptFinished struct {
	ScriptFinished *ScriptFinished `protobuf:"bytes,10,opt,name=script_finished,json=scriptFinished,proto3,oneof"`
}

func (*Message_Exception) isMessage_Type() {}

func (*Message_InitializeHost) isMessage_Type() {}

func (*Message_InitializeHostCompleted) isMessage_Type() {}

func (*Message_InitializeClient) isMessage_Type() {}

func (*Message_InitializeClientCompleted) isMessage_Type() {}

func (*Message_RenderWidget) isMessage_Type() {}

func (*Message_RerunPage) isMessage_Type() {}

func (*Message_CloseSession) isMessage_Type() {}

func (*Message_ScriptFinished) isMessage_Type() {}

type InitializeHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SdkName       string                 `protobuf:"bytes,2,opt,name=sdk_name,json=sdkName,proto3" json:"sdk_name,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Pages         []*v11.Page            `protobuf:"bytes,4,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeHost) Reset() {
	*x = InitializeHost{}
	mi := &file_websocket_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeHost) ProtoMessage() {}

func (x *InitializeHost) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeHost.ProtoReflect.Descriptor instead.
func (*InitializeHost) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeHost) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *InitializeHost) GetSdkName() string {
	if x != nil {
		return x.SdkName
	}
	return ""
}

func (x *InitializeHost) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *InitializeHost) GetPages() []*v11.Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type InitializeHostCompleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostInstanceId string                 `protobuf:"bytes,1,opt,name=host_instance_id,json=hostInstanceId,proto3" json:"host_instance_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitializeHostCompleted) Reset() {
	*x = InitializeHostCompleted{}
	mi := &file_websocket_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeHostCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeHostCompleted) ProtoMessage() {}

func (x *InitializeHostCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeHostCompleted.ProtoReflect.Descriptor instead.
func (*InitializeHostCompleted) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeHostCompleted) GetHostInstanceId() string {
	if x != nil {
		return x.HostInstanceId
	}
	return ""
}

type InitializeClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeClient) Reset() {
	*x = InitializeClient{}
	mi := &file_websocket_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeClient) ProtoMessage() {}

func (x *InitializeClient) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeClient.ProtoReflect.Descriptor instead.
func (*InitializeClient) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeClient) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *InitializeClient) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type InitializeClientCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeClientCompleted) Reset() {
	*x = InitializeClientCompleted{}
	mi := &file_websocket_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeClientCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeClientCompleted) ProtoMessage() {}

func (x *InitializeClientCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeClientCompleted.ProtoReflect.Descriptor instead.
func (*InitializeClientCompleted) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeClientCompleted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RenderWidget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Path          []int32                `protobuf:"varint,3,rep,packed,name=path,proto3" json:"path,omitempty"`
	Widget        *v12.Widget            `protobuf:"bytes,4,opt,name=widget,proto3" json:"widget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderWidget) Reset() {
	*x = RenderWidget{}
	mi := &file_websocket_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderWidget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderWidget) ProtoMessage() {}

func (x *RenderWidget) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderWidget.ProtoReflect.Descriptor instead.
func (*RenderWidget) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *RenderWidget) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RenderWidget) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *RenderWidget) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RenderWidget) GetWidget() *v12.Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

type RerunPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	States        []*v12.Widget          `protobuf:"bytes,3,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerunPage) Reset() {
	*x = RerunPage{}
	mi := &file_websocket_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerunPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerunPage) ProtoMessage() {}

func (x *RerunPage) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerunPage.ProtoReflect.Descriptor instead.
func (*RerunPage) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *RerunPage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RerunPage) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *RerunPage) GetStates() []*v12.Widget {
	if x != nil {
		return x.States
	}
	return nil
}

type CloseSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSession) Reset() {
	*x = CloseSession{}
	mi := &file_websocket_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSession) ProtoMessage() {}

func (x *CloseSession) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSession.ProtoReflect.Descriptor instead.
func (*CloseSession) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *CloseSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ScriptFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        ScriptFinished_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=websocket.v1.ScriptFinished_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptFinished) Reset() {
	*x = ScriptFinished{}
	mi := &file_websocket_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptFinished) ProtoMessage() {}

func (x *ScriptFinished) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptFinished.ProtoReflect.Descriptor instead.
func (*ScriptFinished) Descriptor() ([]byte, []int) {
	return file_websocket_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *ScriptFinished) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScriptFinished) GetStatus() ScriptFinished_Status {
	if x != nil {
		return x.Status
	}
	return ScriptFinished_STATUS_UNSPECIFIED
}

var File_websocket_v1_message_proto protoreflect.FileDescriptor

const file_websocket_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1awebsocket/v1/message.proto\x12\fwebsocket.v1\x1a\x1cexception/v1/exception.proto\x1a\x12page/v1/page.proto\x1a\x16widget/v1/widget.proto\"\xcb\x05\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\texception\x18\x02 \x01(\v2\x17.exception.v1.ExceptionH\x00R\texception\x12G\n" +
	"\x0finitialize_host\x18\x03 \x01(\v2\x1c.websocket.v1.InitializeHostH\x00R\x0einitializeHost\x12c\n" +
	"\x19initialize_host_completed\x18\x04 \x01(\v2%.websocket.v1.InitializeHostCompletedH\x00R\x17initializeHostCompleted\x12M\n" +
	"\x11initialize_client\x18\x05 \x01(\v2\x1e.websocket.v1.InitializeClientH\x00R\x10initializeClient\x12i\n" +
	"\x1binitialize_client_completed\x18\x06 \x01(\v2'.websocket.v1.InitializeClientCompletedH\x00R\x19initializeClientCompleted\x12A\n" +
	"\rrender_widget\x18\a \x01(\v2\x1a.websocket.v1.RenderWidgetH\x00R\frenderWidget\x128\n" +
	"\n" +
	"rerun_page\x18\b \x01(\v2\x17.websocket.v1.RerunPageH\x00R\trerunPage\x12A\n" +
	"\rclose_session\x18\t \x01(\v2\x1a.websocket.v1.CloseSessionH\x00R\fcloseSession\x12G\n" +
	"\x0fscript_finished\x18\n" +
	" \x01(\v2\x1c.websocket.v1.ScriptFinishedH\x00R\x0escriptFinishedB\x06\n" +
	"\x04type\"\x8a\x01\n" +
	"\x0eInitializeHost\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bsdk_name\x18\x02 \x01(\tR\asdkName\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\x12#\n" +
	"\x05pages\x18\x04 \x03(\v2\r.page.v1.PageR\x05pages\"C\n" +
	"\x17InitializeHostCompleted\x12(\n" +
	"\x10host_instance_id\x18\x01 \x01(\tR\x0ehostInstanceId\"^\n" +
	"\x10InitializeClient\x12\"\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageIdB\r\n" +
	"\v_session_id\":\n" +
	"\x19InitializeClientCompleted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x85\x01\n" +
	"\fRenderWidget\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\x12\x12\n" +
	"\x04path\x18\x03 \x03(\x05R\x04path\x12)\n" +
	"\x06widget\x18\x04 \x01(\v2\x11.widget.v1.WidgetR\x06widget\"n\n" +
	"\tRerunPage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\x12)\n" +
	"\x06states\x18\x03 \x03(\v2\x11.widget.v1.WidgetR\x06states\"-\n" +
	"\fCloseSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb6\x01\n" +
	"\x0eScriptFinished\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.websocket.v1.ScriptFinished.StatusR\x06status\"H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n" +
	"\x0eSTATUS_FAILURE\x10\x02B\xbe\x01\n" +
	"\x10com.websocket.v1B\fMessageProtoP\x01ZKgithub.com/trysourcetool/sourcetool-go/internal/pb/websocket/v1;websocketv1\xa2\x02\x03WXX\xaa\x02\fWebsocket.V1\xca\x02\fWebsocket\\V1\xe2\x02\x18Websocket\\V1\\GPBMetadata\xea\x02\rWebsocket::V1b\x06proto3"

var (
	file_websocket_v1_message_proto_rawDescOnce sync.Once
	file_websocket_v1_message_proto_rawDescData []byte
)

func file_websocket_v1_message_proto_rawDescGZIP() []byte {
	file_websocket_v1_message_proto_rawDescOnce.Do(func() {
		file_websocket_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_v1_message_proto_rawDesc), len(file_websocket_v1_message_proto_rawDesc)))
	})
	return file_websocket_v1_message_proto_rawDescData
}

var file_websocket_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_websocket_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_websocket_v1_message_proto_goTypes = []any{
	(ScriptFinished_Status)(0),        // 0: websocket.v1.ScriptFinished.Status
	(*Message)(nil),                   // 1: websocket.v1.Message
	(*InitializeHost)(nil),            // 2: websocket.v1.InitializeHost
	(*InitializeHostCompleted)(nil),   // 3: websocket.v1.InitializeHostCompleted
	(*InitializeClient)(nil),          // 4: websocket.v1.InitializeClient
	(*InitializeClientCompleted)(nil), // 5: websocket.v1.InitializeClientCompleted
	(*RenderWidget)(nil),              // 6: websocket.v1.RenderWidget
	(*RerunPage)(nil),                 // 7: websocket.v1.RerunPage
	(*CloseSession)(nil),              // 8: websocket.v1.CloseSession
	(*ScriptFinished)(nil),            // 9: websocket.v1.ScriptFinished
	(*v1.Exception)(nil),              // 10: exception.v1.Exception
	(*v11.Page)(nil),                  // 11: page.v1.Page
	(*v12.Widget)(nil),                // 12: widget.v1.Widget
}
var file_websocket_v1_message_proto_depIdxs = []int32{
	10, // 0: websocket.v1.Message.exception:type_name -> exception.v1.Exception
	2,  // 1: websocket.v1.Message.initialize_host:type_name -> websocket.v1.InitializeHost
	3,  // 2: websocket.v1.Message.initialize_host_completed:type_name -> websocket.v1.InitializeHostCompleted
	4,  // 3: websocket.v1.Message.initialize_client:type_name -> websocket.v1.InitializeClient
	5,  // 4: websocket.v1.Message.initialize_client_completed:type_name -> websocket.v1.InitializeClientCompleted
	6,  // 5: websocket.v1.Message.render_widget:type_name -> websocket.v1.RenderWidget
	7,  // 6: websocket.v1.Message.rerun_page:type_name -> websocket.v1.RerunPage
	8,  // 7: websocket.v1.Message.close_session:type_name -> websocket.v1.CloseSession
	9,  // 8: websocket.v1.Message.script_finished:type_name -> websocket.v1.ScriptFinished
	11, // 9: websocket.v1.InitializeHost.pages:type_name -> page.v1.Page
	12, // 10: websocket.v1.RenderWidget.widget:type_name -> widget.v1.Widget
	12, // 11: websocket.v1.RerunPage.states:type_name -> widget.v1.Widget
	0,  // 12: websocket.v1.ScriptFinished.status:type_name -> websocket.v1.ScriptFinished.Status
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_websocket_v1_message_proto_init() }
func file_websocket_v1_message_proto_init() {
	if File_websocket_v1_message_proto != nil {
		return
	}
	file_websocket_v1_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Exception)(nil),
		(*Message_InitializeHost)(nil),
		(*Message_InitializeHostCompleted)(nil),
		(*Message_InitializeClient)(nil),
		(*Message_InitializeClientCompleted)(nil),
		(*Message_RenderWidget)(nil),
		(*Message_RerunPage)(nil),
		(*Message_CloseSession)(nil),
		(*Message_ScriptFinished)(nil),
	}
	file_websocket_v1_message_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_v1_message_proto_rawDesc), len(file_websocket_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_websocket_v1_message_proto_goTypes,
		DependencyIndexes: file_websocket_v1_message_proto_depIdxs,
		EnumInfos:         file_websocket_v1_message_proto_enumTypes,
		MessageInfos:      file_websocket_v1_message_proto_msgTypes,
	}.Build()
	File_websocket_v1_message_proto = out.File
	file_websocket_v1_message_proto_goTypes = nil
	file_websocket_v1_message_proto_depIdxs = nil
}
