// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: exception/v1/exception.proto

package exceptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exception struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StackTrace    []string               `protobuf:"bytes,3,rep,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exception) Reset() {
	*x = Exception{}
	mi := &file_exception_v1_exception_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exception) ProtoMessage() {}

func (x *Exception) ProtoReflect() protoreflect.Message {
	mi := &file_exception_v1_exception_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exception.ProtoReflect.Descriptor instead.
func (*Exception) Descriptor() ([]byte, []int) {
	return file_exception_v1_exception_proto_rawDescGZIP(), []int{0}
}

func (x *Exception) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Exception) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Exception) GetStackTrace() []string {
	if x != nil {
		return x.StackTrace
	}
	return nil
}

func (x *Exception) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_exception_v1_exception_proto protoreflect.FileDescriptor

const file_exception_v1_exception_proto_rawDesc = "" +
	"\n" +
	"\x1cexception/v1/exception.proto\x12\fexception.v1\"{\n" +
	"\tException\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x03(\tR\n" +
	"stackTrace\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionIdB\xc2\x01\n" +
	"\x10com.exception.v1B\x0eExceptionProtoP\x01ZKgithub.com/trysourcetool/sourcetool-go/internal/pb/exception/v1;exceptionv1\xa2\x02\x03EXX\xaa\x02\fException.V1\xca\x02\rException_\\V1\xe2\x02\x19Exception_\\V1\\GPBMetadata\xea\x02\rException::V1b\x06proto3"

var (
	file_exception_v1_exception_proto_rawDescOnce sync.Once
	file_exception_v1_exception_proto_rawDescData []byte
)

func file_exception_v1_exception_proto_rawDescGZIP() []byte {
	file_exception_v1_exception_proto_rawDescOnce.Do(func() {
		file_exception_v1_exception_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exception_v1_exception_proto_rawDesc), len(file_exception_v1_exception_proto_rawDesc)))
	})
	return file_exception_v1_exception_proto_rawDescData
}

var file_exception_v1_exception_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exception_v1_exception_proto_goTypes = []any{
	(*Exception)(nil), // 0: exception.v1.Exception
}
var file_exception_v1_exception_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exception_v1_exception_proto_init() }
func file_exception_v1_exception_proto_init() {
	if File_exception_v1_exception_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exception_v1_exception_proto_rawDesc), len(file_exception_v1_exception_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exception_v1_exception_proto_goTypes,
		DependencyIndexes: file_exception_v1_exception_proto_depIdxs,
		MessageInfos:      file_exception_v1_exception_proto_msgTypes,
	}.Build()
	File_exception_v1_exception_proto = out.File
	file_exception_v1_exception_proto_goTypes = nil
	file_exception_v1_exception_proto_depIdxs = nil
}
