// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: widget/v1/widget.proto

package widgetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Button struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Disabled      bool                   `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Button) Reset() {
	*x = Button{}
	mi := &file_widget_v1_widget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Button) ProtoMessage() {}

func (x *Button) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Button.ProtoReflect.Descriptor instead.
func (*Button) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{0}
}

func (x *Button) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *Button) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Button) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Checkbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	DefaultValue  bool                   `protobuf:"varint,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkbox) Reset() {
	*x = Checkbox{}
	mi := &file_widget_v1_widget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkbox) ProtoMessage() {}

func (x *Checkbox) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkbox.ProtoReflect.Descriptor instead.
func (*Checkbox) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{1}
}

func (x *Checkbox) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *Checkbox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Checkbox) GetDefaultValue() bool {
	if x != nil {
		return x.DefaultValue
	}
	return false
}

func (x *Checkbox) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Checkbox) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type CheckboxGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []int32                `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	DefaultValue  []int32                `protobuf:"varint,4,rep,packed,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckboxGroup) Reset() {
	*x = CheckboxGroup{}
	mi := &file_widget_v1_widget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckboxGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckboxGroup) ProtoMessage() {}

func (x *CheckboxGroup) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckboxGroup.ProtoReflect.Descriptor instead.
func (*CheckboxGroup) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{2}
}

func (x *CheckboxGroup) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CheckboxGroup) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CheckboxGroup) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CheckboxGroup) GetDefaultValue() []int32 {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *CheckboxGroup) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CheckboxGroup) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type ColumnItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float64                `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnItem) Reset() {
	*x = ColumnItem{}
	mi := &file_widget_v1_widget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnItem) ProtoMessage() {}

func (x *ColumnItem) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnItem.ProtoReflect.Descriptor instead.
func (*ColumnItem) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Columns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       int32                  `protobuf:"varint,1,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Columns) Reset() {
	*x = Columns{}
	mi := &file_widget_v1_widget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Columns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Columns) ProtoMessage() {}

func (x *Columns) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Columns.ProtoReflect.Descriptor instead.
func (*Columns) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{4}
}

func (x *Columns) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type DateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder   string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  *string                `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Format        string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	MaxValue      string                 `protobuf:"bytes,8,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MinValue      string                 `protobuf:"bytes,9,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateInput) Reset() {
	*x = DateInput{}
	mi := &file_widget_v1_widget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateInput) ProtoMessage() {}

func (x *DateInput) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateInput.ProtoReflect.Descriptor instead.
func (*DateInput) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{5}
}

func (x *DateInput) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *DateInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DateInput) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *DateInput) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *DateInput) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *DateInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *DateInput) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DateInput) GetMaxValue() string {
	if x != nil {
		return x.MaxValue
	}
	return ""
}

func (x *DateInput) GetMinValue() string {
	if x != nil {
		return x.MinValue
	}
	return ""
}

type DateTimeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder   string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  *string                `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Format        string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	MaxValue      string                 `protobuf:"bytes,8,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MinValue      string                 `protobuf:"bytes,9,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTimeInput) Reset() {
	*x = DateTimeInput{}
	mi := &file_widget_v1_widget_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTimeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTimeInput) ProtoMessage() {}

func (x *DateTimeInput) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTimeInput.ProtoReflect.Descriptor instead.
func (*DateTimeInput) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{6}
}

func (x *DateTimeInput) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *DateTimeInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DateTimeInput) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *DateTimeInput) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *DateTimeInput) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *DateTimeInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *DateTimeInput) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DateTimeInput) GetMaxValue() string {
	if x != nil {
		return x.MaxValue
	}
	return ""
}

func (x *DateTimeInput) GetMinValue() string {
	if x != nil {
		return x.MinValue
	}
	return ""
}

type Form struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Value          bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	ButtonLabel    string                 `protobuf:"bytes,2,opt,name=button_label,json=buttonLabel,proto3" json:"button_label,omitempty"`
	ButtonDisabled bool                   `protobuf:"varint,3,opt,name=button_disabled,json=buttonDisabled,proto3" json:"button_disabled,omitempty"`
	ClearOnSubmit  bool                   `protobuf:"varint,4,opt,name=clear_on_submit,json=clearOnSubmit,proto3" json:"clear_on_submit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Form) Reset() {
	*x = Form{}
	mi := &file_widget_v1_widget_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Form) ProtoMessage() {}

func (x *Form) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Form.ProtoReflect.Descriptor instead.
func (*Form) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{7}
}

func (x *Form) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *Form) GetButtonLabel() string {
	if x != nil {
		return x.ButtonLabel
	}
	return ""
}

func (x *Form) GetButtonDisabled() bool {
	if x != nil {
		return x.ButtonDisabled
	}
	return false
}

func (x *Form) GetClearOnSubmit() bool {
	if x != nil {
		return x.ClearOnSubmit
	}
	return false
}

type Markdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Markdown) Reset() {
	*x = Markdown{}
	mi := &file_widget_v1_widget_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Markdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Markdown) ProtoMessage() {}

func (x *Markdown) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Markdown.ProtoReflect.Descriptor instead.
func (*Markdown) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{8}
}

func (x *Markdown) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type MultiSelect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []int32                `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Placeholder   string                 `protobuf:"bytes,4,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  []int32                `protobuf:"varint,5,rep,packed,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSelect) Reset() {
	*x = MultiSelect{}
	mi := &file_widget_v1_widget_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSelect) ProtoMessage() {}

func (x *MultiSelect) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSelect.ProtoReflect.Descriptor instead.
func (*MultiSelect) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{9}
}

func (x *MultiSelect) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MultiSelect) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MultiSelect) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MultiSelect) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *MultiSelect) GetDefaultValue() []int32 {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *MultiSelect) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *MultiSelect) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type NumberInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float64               `protobuf:"fixed64,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder   string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  *float64               `protobuf:"fixed64,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	MaxValue      *float64               `protobuf:"fixed64,7,opt,name=max_value,json=maxValue,proto3,oneof" json:"max_value,omitempty"`
	MinValue      *float64               `protobuf:"fixed64,8,opt,name=min_value,json=minValue,proto3,oneof" json:"min_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberInput) Reset() {
	*x = NumberInput{}
	mi := &file_widget_v1_widget_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberInput) ProtoMessage() {}

func (x *NumberInput) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberInput.ProtoReflect.Descriptor instead.
func (*NumberInput) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{10}
}

func (x *NumberInput) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *NumberInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NumberInput) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *NumberInput) GetDefaultValue() float64 {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return 0
}

func (x *NumberInput) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *NumberInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *NumberInput) GetMaxValue() float64 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

func (x *NumberInput) GetMinValue() float64 {
	if x != nil && x.MinValue != nil {
		return *x.MinValue
	}
	return 0
}

type Radio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	DefaultValue  *int32                 `protobuf:"varint,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Radio) Reset() {
	*x = Radio{}
	mi := &file_widget_v1_widget_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Radio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Radio) ProtoMessage() {}

func (x *Radio) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Radio.ProtoReflect.Descriptor instead.
func (*Radio) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{11}
}

func (x *Radio) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Radio) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Radio) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Radio) GetDefaultValue() int32 {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return 0
}

func (x *Radio) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Radio) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Selectbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Placeholder   string                 `protobuf:"bytes,4,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  *int32                 `protobuf:"varint,5,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selectbox) Reset() {
	*x = Selectbox{}
	mi := &file_widget_v1_widget_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selectbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selectbox) ProtoMessage() {}

func (x *Selectbox) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selectbox.ProtoReflect.Descriptor instead.
func (*Selectbox) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{12}
}

func (x *Selectbox) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Selectbox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Selectbox) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Selectbox) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *Selectbox) GetDefaultValue() int32 {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return 0
}

func (x *Selectbox) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Selectbox) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Value         *TableValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Header        string                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Height        *int32                 `protobuf:"varint,5,opt,name=height,proto3,oneof" json:"height,omitempty"`
	ColumnOrder   []string               `protobuf:"bytes,6,rep,name=column_order,json=columnOrder,proto3" json:"column_order,omitempty"`
	OnSelect      string                 `protobuf:"bytes,7,opt,name=on_select,json=onSelect,proto3" json:"on_select,omitempty"`
	RowSelection  string                 `protobuf:"bytes,8,opt,name=row_selection,json=rowSelection,proto3" json:"row_selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_widget_v1_widget_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{13}
}

func (x *Table) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Table) GetValue() *TableValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Table) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Table) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Table) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Table) GetColumnOrder() []string {
	if x != nil {
		return x.ColumnOrder
	}
	return nil
}

func (x *Table) GetOnSelect() string {
	if x != nil {
		return x.OnSelect
	}
	return ""
}

func (x *Table) GetRowSelection() string {
	if x != nil {
		return x.RowSelection
	}
	return ""
}

type TableValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selection     *TableValueSelection   `protobuf:"bytes,1,opt,name=selection,proto3,oneof" json:"selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableValue) Reset() {
	*x = TableValue{}
	mi := &file_widget_v1_widget_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableValue) ProtoMessage() {}

func (x *TableValue) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableValue.ProtoReflect.Descriptor instead.
func (*TableValue) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{14}
}

func (x *TableValue) GetSelection() *TableValueSelection {
	if x != nil {
		return x.Selection
	}
	return nil
}

type TableValueSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Rows          []int32                `protobuf:"varint,2,rep,packed,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableValueSelection) Reset() {
	*x = TableValueSelection{}
	mi := &file_widget_v1_widget_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableValueSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableValueSelection) ProtoMessage() {}

func (x *TableValueSelection) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableValueSelection.ProtoReflect.Descriptor instead.
func (*TableValueSelection) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{15}
}

func (x *TableValueSelection) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *TableValueSelection) GetRows() []int32 {
	if x != nil {
		return x.Rows
	}
	return nil
}

type TextArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder   string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  *string                `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,7,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	MinLength     *int32                 `protobuf:"varint,8,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	MaxLines      *int32                 `protobuf:"varint,9,opt,name=max_lines,json=maxLines,proto3,oneof" json:"max_lines,omitempty"`
	MinLines      *int32                 `protobuf:"varint,10,opt,name=min_lines,json=minLines,proto3,oneof" json:"min_lines,omitempty"`
	AutoResize    bool                   `protobuf:"varint,11,opt,name=auto_resize,json=autoResize,proto3" json:"auto_resize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextArea) Reset() {
	*x = TextArea{}
	mi := &file_widget_v1_widget_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextArea) ProtoMessage() {}

func (x *TextArea) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextArea.ProtoReflect.Descriptor instead.
func (*TextArea) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{16}
}

func (x *TextArea) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *TextArea) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TextArea) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *TextArea) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *TextArea) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *TextArea) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *TextArea) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *TextArea) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *TextArea) GetMaxLines() int32 {
	if x != nil && x.MaxLines != nil {
		return *x.MaxLines
	}
	return 0
}

func (x *TextArea) GetMinLines() int32 {
	if x != nil && x.MinLines != nil {
		return *x.MinLines
	}
	return 0
}

func (x *TextArea) GetAutoResize() bool {
	if x != nil {
		return x.AutoResize
	}
	return false
}

type TextInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder   string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  *string                `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	MaxLength     *int32                 `protobuf:"varint,7,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	MinLength     *int32                 `protobuf:"varint,8,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInput) Reset() {
	*x = TextInput{}
	mi := &file_widget_v1_widget_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInput) ProtoMessage() {}

func (x *TextInput) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInput.ProtoReflect.Descriptor instead.
func (*TextInput) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{17}
}

func (x *TextInput) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *TextInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TextInput) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *TextInput) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *TextInput) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *TextInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *TextInput) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *TextInput) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

type TimeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Placeholder   string                 `protobuf:"bytes,3,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  *string                `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Disabled      bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeInput) Reset() {
	*x = TimeInput{}
	mi := &file_widget_v1_widget_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeInput) ProtoMessage() {}

func (x *TimeInput) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeInput.ProtoReflect.Descriptor instead.
func (*TimeInput) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{18}
}

func (x *TimeInput) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *TimeInput) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimeInput) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *TimeInput) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *TimeInput) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *TimeInput) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Widget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Widget_Button
	//	*Widget_Checkbox
	//	*Widget_CheckboxGroup
	//	*Widget_ColumnItem
	//	*Widget_Columns
	//	*Widget_DateInput
	//	*Widget_DateTimeInput
	//	*Widget_Form
	//	*Widget_Markdown
	//	*Widget_MultiSelect
	//	*Widget_NumberInput
	//	*Widget_Radio
	//	*Widget_Selectbox
	//	*Widget_Table
	//	*Widget_TextArea
	//	*Widget_TextInput
	//	*Widget_TimeInput
	Type          isWidget_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_widget_v1_widget_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_widget_v1_widget_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_widget_v1_widget_proto_rawDescGZIP(), []int{19}
}

func (x *Widget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Widget) GetType() isWidget_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Widget) GetButton() *Button {
	if x != nil {
		if x, ok := x.Type.(*Widget_Button); ok {
			return x.Button
		}
	}
	return nil
}

func (x *Widget) GetCheckbox() *Checkbox {
	if x != nil {
		if x, ok := x.Type.(*Widget_Checkbox); ok {
			return x.Checkbox
		}
	}
	return nil
}

func (x *Widget) GetCheckboxGroup() *CheckboxGroup {
	if x != nil {
		if x, ok := x.Type.(*Widget_CheckboxGroup); ok {
			return x.CheckboxGroup
		}
	}
	return nil
}

func (x *Widget) GetColumnItem() *ColumnItem {
	if x != nil {
		if x, ok := x.Type.(*Widget_ColumnItem); ok {
			return x.ColumnItem
		}
	}
	return nil
}

func (x *Widget) GetColumns() *Columns {
	if x != nil {
		if x, ok := x.Type.(*Widget_Columns); ok {
			return x.Columns
		}
	}
	return nil
}

func (x *Widget) GetDateInput() *DateInput {
	if x != nil {
		if x, ok := x.Type.(*Widget_DateInput); ok {
			return x.DateInput
		}
	}
	return nil
}

func (x *Widget) GetDateTimeInput() *DateTimeInput {
	if x != nil {
		if x, ok := x.Type.(*Widget_DateTimeInput); ok {
			return x.DateTimeInput
		}
	}
	return nil
}

func (x *Widget) GetForm() *Form {
	if x != nil {
		if x, ok := x.Type.(*Widget_Form); ok {
			return x.Form
		}
	}
	return nil
}

func (x *Widget) GetMarkdown() *Markdown {
	if x != nil {
		if x, ok := x.Type.(*Widget_Markdown); ok {
			return x.Markdown
		}
	}
	return nil
}

func (x *Widget) GetMultiSelect() *MultiSelect {
	if x != nil {
		if x, ok := x.Type.(*Widget_MultiSelect); ok {
			return x.MultiSelect
		}
	}
	return nil
}

func (x *Widget) GetNumberInput() *NumberInput {
	if x != nil {
		if x, ok := x.Type.(*Widget_NumberInput); ok {
			return x.NumberInput
		}
	}
	return nil
}

func (x *Widget) GetRadio() *Radio {
	if x != nil {
		if x, ok := x.Type.(*Widget_Radio); ok {
			return x.Radio
		}
	}
	return nil
}

func (x *Widget) GetSelectbox() *Selectbox {
	if x != nil {
		if x, ok := x.Type.(*Widget_Selectbox); ok {
			return x.Selectbox
		}
	}
	return nil
}

func (x *Widget) GetTable() *Table {
	if x != nil {
		if x, ok := x.Type.(*Widget_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *Widget) GetTextArea() *TextArea {
	if x != nil {
		if x, ok := x.Type.(*Widget_TextArea); ok {
			return x.TextArea
		}
	}
	return nil
}

func (x *Widget) GetTextInput() *TextInput {
	if x != nil {
		if x, ok := x.Type.(*Widget_TextInput); ok {
			return x.TextInput
		}
	}
	return nil
}

func (x *Widget) GetTimeInput() *TimeInput {
	if x != nil {
		if x, ok := x.Type.(*Widget_TimeInput); ok {
			return x.TimeInput
		}
	}
	return nil
}

type isWidget_Type interface {
	isWidget_Type()
}

type Widget_Button struct {
	Button *Button `protobuf:"bytes,2,opt,name=button,proto3,oneof"`
}

type Widget_Checkbox struct {
	Checkbox *Checkbox `protobuf:"bytes,3,opt,name=checkbox,proto3,oneof"`
}

type Widget_CheckboxGroup struct {
	CheckboxGroup *CheckboxGroup `protobuf:"bytes,4,opt,name=checkbox_group,json=checkboxGroup,proto3,oneof"`
}

type Widget_ColumnItem struct {
	ColumnItem *ColumnItem `protobuf:"bytes,5,opt,name=column_item,json=columnItem,proto3,oneof"`
}

type Widget_Columns struct {
	Columns *Columns `protobuf:"bytes,6,opt,name=columns,proto3,oneof"`
}

type Widget_DateInput struct {
	DateInput *DateInput `protobuf:"bytes,7,opt,name=date_input,json=dateInput,proto3,oneof"`
}

type Widget_DateTimeInput struct {
	DateTimeInput *DateTimeInput `protobuf:"bytes,8,opt,name=date_time_input,json=dateTimeInput,proto3,oneof"`
}

type Widget_Form struct {
	Form *Form `protobuf:"bytes,9,opt,name=form,proto3,oneof"`
}

type Widget_Markdown struct {
	Markdown *Markdown `protobuf:"bytes,10,opt,name=markdown,proto3,oneof"`
}

type Widget_MultiSelect struct {
	MultiSelect *MultiSelect `protobuf:"bytes,11,opt,name=multi_select,json=multiSelect,proto3,oneof"`
}

type Widget_NumberInput struct {
	NumberInput *NumberInput `protobuf:"bytes,12,opt,name=number_input,json=numberInput,proto3,oneof"`
}

type Widget_Radio struct {
	Radio *Radio `protobuf:"bytes,13,opt,name=radio,proto3,oneof"`
}

type Widget_Selectbox struct {
	Selectbox *Selectbox `protobuf:"bytes,14,opt,name=selectbox,proto3,oneof"`
}

type Widget_Table struct {
	Table *Table `protobuf:"bytes,15,opt,name=table,proto3,oneof"`
}

type Widget_TextArea struct {
	TextArea *TextArea `protobuf:"bytes,16,opt,name=text_area,json=textArea,proto3,oneof"`
}

type Widget_TextInput struct {
	TextInput *TextInput `protobuf:"bytes,17,opt,name=text_input,json=textInput,proto3,oneof"`
}

type Widget_TimeInput struct {
	TimeInput *TimeInput `protobuf:"bytes,18,opt,name=time_input,json=timeInput,proto3,oneof"`
}

func (*Widget_Button) isWidget_Type() {}

func (*Widget_Checkbox) isWidget_Type() {}

func (*Widget_CheckboxGroup) isWidget_Type() {}

func (*Widget_ColumnItem) isWidget_Type() {}

func (*Widget_Columns) isWidget_Type() {}

func (*Widget_DateInput) isWidget_Type() {}

func (*Widget_DateTimeInput) isWidget_Type() {}

func (*Widget_Form) isWidget_Type() {}

func (*Widget_Markdown) isWidget_Type() {}

func (*Widget_MultiSelect) isWidget_Type() {}

func (*Widget_NumberInput) isWidget_Type() {}

func (*Widget_Radio) isWidget_Type() {}

func (*Widget_Selectbox) isWidget_Type() {}

func (*Widget_Table) isWidget_Type() {}

func (*Widget_TextArea) isWidget_Type() {}

func (*Widget_TextInput) isWidget_Type() {}

func (*Widget_TimeInput) isWidget_Type() {}

var File_widget_v1_widget_proto protoreflect.FileDescriptor

const file_widget_v1_widget_proto_rawDesc = "" +
	"\n" +
	"\x16widget/v1/widget.proto\x12\twidget.v1\"P\n" +
	"\x06Button\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\"\x93\x01\n" +
	"\bCheckbox\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\bR\fdefaultValue\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\"\xb2\x01\n" +
	"\rCheckboxGroup\x12\x14\n" +
	"\x05value\x18\x01 \x03(\x05R\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12#\n" +
	"\rdefault_value\x18\x04 \x03(\x05R\fdefaultValue\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\"$\n" +
	"\n" +
	"ColumnItem\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x01R\x06weight\"#\n" +
	"\aColumns\x12\x18\n" +
	"\acolumns\x18\x01 \x01(\x05R\acolumns\"\xae\x02\n" +
	"\tDateInput\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12(\n" +
	"\rdefault_value\x18\x04 \x01(\tH\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x1b\n" +
	"\tmax_value\x18\b \x01(\tR\bmaxValue\x12\x1b\n" +
	"\tmin_value\x18\t \x01(\tR\bminValueB\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_value\"\xb2\x02\n" +
	"\rDateTimeInput\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12(\n" +
	"\rdefault_value\x18\x04 \x01(\tH\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x1b\n" +
	"\tmax_value\x18\b \x01(\tR\bmaxValue\x12\x1b\n" +
	"\tmin_value\x18\t \x01(\tR\bminValueB\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_value\"\x90\x01\n" +
	"\x04Form\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12!\n" +
	"\fbutton_label\x18\x02 \x01(\tR\vbuttonLabel\x12'\n" +
	"\x0fbutton_disabled\x18\x03 \x01(\bR\x0ebuttonDisabled\x12&\n" +
	"\x0fclear_on_submit\x18\x04 \x01(\bR\rclearOnSubmit\"\x1e\n" +
	"\bMarkdown\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"\xd2\x01\n" +
	"\vMultiSelect\x12\x14\n" +
	"\x05value\x18\x01 \x03(\x05R\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12 \n" +
	"\vplaceholder\x18\x04 \x01(\tR\vplaceholder\x12#\n" +
	"\rdefault_value\x18\x05 \x03(\x05R\fdefaultValue\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\"\xbe\x02\n" +
	"\vNumberInput\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x01H\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12(\n" +
	"\rdefault_value\x18\x04 \x01(\x01H\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12 \n" +
	"\tmax_value\x18\a \x01(\x01H\x02R\bmaxValue\x88\x01\x01\x12 \n" +
	"\tmin_value\x18\b \x01(\x01H\x03R\bminValue\x88\x01\x01B\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_valueB\f\n" +
	"\n" +
	"_max_valueB\f\n" +
	"\n" +
	"_min_value\"\xd0\x01\n" +
	"\x05Radio\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x05H\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12(\n" +
	"\rdefault_value\x18\x04 \x01(\x05H\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabledB\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_value\"\xf6\x01\n" +
	"\tSelectbox\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x05H\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12 \n" +
	"\vplaceholder\x18\x04 \x01(\tR\vplaceholder\x12(\n" +
	"\rdefault_value\x18\x05 \x01(\x05H\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabledB\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_value\"\x8f\x02\n" +
	"\x05Table\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.widget.v1.TableValueR\x05value\x12\x16\n" +
	"\x06header\x18\x03 \x01(\tR\x06header\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\x06height\x18\x05 \x01(\x05H\x00R\x06height\x88\x01\x01\x12!\n" +
	"\fcolumn_order\x18\x06 \x03(\tR\vcolumnOrder\x12\x1b\n" +
	"\ton_select\x18\a \x01(\tR\bonSelect\x12#\n" +
	"\rrow_selection\x18\b \x01(\tR\frowSelectionB\t\n" +
	"\a_height\"]\n" +
	"\n" +
	"TableValue\x12A\n" +
	"\tselection\x18\x01 \x01(\v2\x1e.widget.v1.TableValueSelectionH\x00R\tselection\x88\x01\x01B\f\n" +
	"\n" +
	"_selection\";\n" +
	"\x13TableValueSelection\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x12\n" +
	"\x04rows\x18\x02 \x03(\x05R\x04rows\"\xc2\x03\n" +
	"\bTextArea\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12(\n" +
	"\rdefault_value\x18\x04 \x01(\tH\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12\"\n" +
	"\n" +
	"max_length\x18\a \x01(\x05H\x02R\tmaxLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_length\x18\b \x01(\x05H\x03R\tminLength\x88\x01\x01\x12 \n" +
	"\tmax_lines\x18\t \x01(\x05H\x04R\bmaxLines\x88\x01\x01\x12 \n" +
	"\tmin_lines\x18\n" +
	" \x01(\x05H\x05R\bminLines\x88\x01\x01\x12\x1f\n" +
	"\vauto_resize\x18\v \x01(\bR\n" +
	"autoResizeB\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_valueB\r\n" +
	"\v_max_lengthB\r\n" +
	"\v_min_lengthB\f\n" +
	"\n" +
	"_max_linesB\f\n" +
	"\n" +
	"_min_lines\"\xc2\x02\n" +
	"\tTextInput\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12(\n" +
	"\rdefault_value\x18\x04 \x01(\tH\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\x12\"\n" +
	"\n" +
	"max_length\x18\a \x01(\x05H\x02R\tmaxLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_length\x18\b \x01(\x05H\x03R\tminLength\x88\x01\x01B\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_valueB\r\n" +
	"\v_max_lengthB\r\n" +
	"\v_min_length\"\xdc\x01\n" +
	"\tTimeInput\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vplaceholder\x18\x03 \x01(\tR\vplaceholder\x12(\n" +
	"\rdefault_value\x18\x04 \x01(\tH\x01R\fdefaultValue\x88\x01\x01\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabledB\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_default_value\"\xa8\a\n" +
	"\x06Widget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x06button\x18\x02 \x01(\v2\x11.widget.v1.ButtonH\x00R\x06button\x121\n" +
	"\bcheckbox\x18\x03 \x01(\v2\x13.widget.v1.CheckboxH\x00R\bcheckbox\x12A\n" +
	"\x0echeckbox_group\x18\x04 \x01(\v2\x18.widget.v1.CheckboxGroupH\x00R\rcheckboxGroup\x128\n" +
	"\vcolumn_item\x18\x05 \x01(\v2\x15.widget.v1.ColumnItemH\x00R\n" +
	"columnItem\x12.\n" +
	"\acolumns\x18\x06 \x01(\v2\x12.widget.v1.ColumnsH\x00R\acolumns\x125\n" +
	"\n" +
	"date_input\x18\a \x01(\v2\x14.widget.v1.DateInputH\x00R\tdateInput\x12B\n" +
	"\x0fdate_time_input\x18\b \x01(\v2\x18.widget.v1.DateTimeInputH\x00R\rdateTimeInput\x12%\n" +
	"\x04form\x18\t \x01(\v2\x0f.widget.v1.FormH\x00R\x04form\x121\n" +
	"\bmarkdown\x18\n" +
	" \x01(\v2\x13.widget.v1.MarkdownH\x00R\bmarkdown\x12;\n" +
	"\fmulti_select\x18\v \x01(\v2\x16.widget.v1.MultiSelectH\x00R\vmultiSelect\x12;\n" +
	"\fnumber_input\x18\f \x01(\v2\x16.widget.v1.NumberInputH\x00R\vnumberInput\x12(\n" +
	"\x05radio\x18\r \x01(\v2\x10.widget.v1.RadioH\x00R\x05radio\x124\n" +
	"\tselectbox\x18\x0e \x01(\v2\x14.widget.v1.SelectboxH\x00R\tselectbox\x12(\n" +
	"\x05table\x18\x0f \x01(\v2\x10.widget.v1.TableH\x00R\x05table\x122\n" +
	"\ttext_area\x18\x10 \x01(\v2\x13.widget.v1.TextAreaH\x00R\btextArea\x125\n" +
	"\n" +
	"text_input\x18\x11 \x01(\v2\x14.widget.v1.TextInputH\x00R\ttextInput\x125\n" +
	"\n" +
	"time_input\x18\x12 \x01(\v2\x14.widget.v1.TimeInputH\x00R\ttimeInputB\x06\n" +
	"\x04typeB\xa8\x01\n" +
	"\rcom.widget.v1B\vWidgetProtoP\x01ZEgithub.com/trysourcetool/sourcetool-go/internal/pb/widget/v1;widgetv1\xa2\x02\x03WXX\xaa\x02\tWidget.V1\xca\x02\tWidget\\V1\xe2\x02\x15Widget\\V1\\GPBMetadata\xea\x02\n" +
	"Widget::V1b\x06proto3"

var (
	file_widget_v1_widget_proto_rawDescOnce sync.Once
	file_widget_v1_widget_proto_rawDescData []byte
)

func file_widget_v1_widget_proto_rawDescGZIP() []byte {
	file_widget_v1_widget_proto_rawDescOnce.Do(func() {
		file_widget_v1_widget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_widget_v1_widget_proto_rawDesc), len(file_widget_v1_widget_proto_rawDesc)))
	})
	return file_widget_v1_widget_proto_rawDescData
}

var file_widget_v1_widget_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_widget_v1_widget_proto_goTypes = []any{
	(*Button)(nil),              // 0: widget.v1.Button
	(*Checkbox)(nil),            // 1: widget.v1.Checkbox
	(*CheckboxGroup)(nil),       // 2: widget.v1.CheckboxGroup
	(*ColumnItem)(nil),          // 3: widget.v1.ColumnItem
	(*Columns)(nil),             // 4: widget.v1.Columns
	(*DateInput)(nil),           // 5: widget.v1.DateInput
	(*DateTimeInput)(nil),       // 6: widget.v1.DateTimeInput
	(*Form)(nil),                // 7: widget.v1.Form
	(*Markdown)(nil),            // 8: widget.v1.Markdown
	(*MultiSelect)(nil),         // 9: widget.v1.MultiSelect
	(*NumberInput)(nil),         // 10: widget.v1.NumberInput
	(*Radio)(nil),               // 11: widget.v1.Radio
	(*Selectbox)(nil),           // 12: widget.v1.Selectbox
	(*Table)(nil),               // 13: widget.v1.Table
	(*TableValue)(nil),          // 14: widget.v1.TableValue
	(*TableValueSelection)(nil), // 15: widget.v1.TableValueSelection
	(*TextArea)(nil),            // 16: widget.v1.TextArea
	(*TextInput)(nil),           // 17: widget.v1.TextInput
	(*TimeInput)(nil),           // 18: widget.v1.TimeInput
	(*Widget)(nil),              // 19: widget.v1.Widget
}
var file_widget_v1_widget_proto_depIdxs = []int32{
	14, // 0: widget.v1.Table.value:type_name -> widget.v1.TableValue
	15, // 1: widget.v1.TableValue.selection:type_name -> widget.v1.TableValueSelection
	0,  // 2: widget.v1.Widget.button:type_name -> widget.v1.Button
	1,  // 3: widget.v1.Widget.checkbox:type_name -> widget.v1.Checkbox
	2,  // 4: widget.v1.Widget.checkbox_group:type_name -> widget.v1.CheckboxGroup
	3,  // 5: widget.v1.Widget.column_item:type_name -> widget.v1.ColumnItem
	4,  // 6: widget.v1.Widget.columns:type_name -> widget.v1.Columns
	5,  // 7: widget.v1.Widget.date_input:type_name -> widget.v1.DateInput
	6,  // 8: widget.v1.Widget.date_time_input:type_name -> widget.v1.DateTimeInput
	7,  // 9: widget.v1.Widget.form:type_name -> widget.v1.Form
	8,  // 10: widget.v1.Widget.markdown:type_name -> widget.v1.Markdown
	9,  // 11: widget.v1.Widget.multi_select:type_name -> widget.v1.MultiSelect
	10, // 12: widget.v1.Widget.number_input:type_name -> widget.v1.NumberInput
	11, // 13: widget.v1.Widget.radio:type_name -> widget.v1.Radio
	12, // 14: widget.v1.Widget.selectbox:type_name -> widget.v1.Selectbox
	13, // 15: widget.v1.Widget.table:type_name -> widget.v1.Table
	16, // 16: widget.v1.Widget.text_area:type_name -> widget.v1.TextArea
	17, // 17: widget.v1.Widget.text_input:type_name -> widget.v1.TextInput
	18, // 18: widget.v1.Widget.time_input:type_name -> widget.v1.TimeInput
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_widget_v1_widget_proto_init() }
func file_widget_v1_widget_proto_init() {
	if File_widget_v1_widget_proto != nil {
		return
	}
	file_widget_v1_widget_proto_msgTypes[5].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[6].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[10].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[11].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[12].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[13].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[14].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[16].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[17].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[18].OneofWrappers = []any{}
	file_widget_v1_widget_proto_msgTypes[19].OneofWrappers = []any{
		(*Widget_Button)(nil),
		(*Widget_Checkbox)(nil),
		(*Widget_CheckboxGroup)(nil),
		(*Widget_ColumnItem)(nil),
		(*Widget_Columns)(nil),
		(*Widget_DateInput)(nil),
		(*Widget_DateTimeInput)(nil),
		(*Widget_Form)(nil),
		(*Widget_Markdown)(nil),
		(*Widget_MultiSelect)(nil),
		(*Widget_NumberInput)(nil),
		(*Widget_Radio)(nil),
		(*Widget_Selectbox)(nil),
		(*Widget_Table)(nil),
		(*Widget_TextArea)(nil),
		(*Widget_TextInput)(nil),
		(*Widget_TimeInput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_widget_v1_widget_proto_rawDesc), len(file_widget_v1_widget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_widget_v1_widget_proto_goTypes,
		DependencyIndexes: file_widget_v1_widget_proto_depIdxs,
		MessageInfos:      file_widget_v1_widget_proto_msgTypes,
	}.Build()
	File_widget_v1_widget_proto = out.File
	file_widget_v1_widget_proto_goTypes = nil
	file_widget_v1_widget_proto_depIdxs = nil
}
